import type { Product, Stat, ProcessStep, ExtendedRangeItem } from '../types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'tomato-powder',
    name: 'Tomato Powder',
    tagline: 'Deep umami, rich lycopene',
    category: 'vegetable',
    swatchColor: 'pw-tomato',
    swatchHex: '#C23B22',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TOM-001',
    mesh: '80 mesh',
    description:
      'Made from ripe Roma tomatoes at peak harvest. Intense color, concentrated flavor — no added salt or sugar.',
    featured: true,
    imageSrc: '/Images/Tomato_Powder.png',
    rawImageSrc: '/Images/Tomato_Powder.png',
    swatchImageSrc: '/Images/Tomato_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Extruder Foods', 'Curries', 'Instant Food Products'],
  },
  {
    id: '2',
    slug: 'onion-powder',
    name: 'Onion Powder',
    tagline: 'Sharp, sulfurous, aromatic',
    category: 'vegetable',
    swatchColor: 'pw-onion',
    swatchHex: '#C9855A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-ONI-002',
    mesh: '80 mesh',
    description:
      'White onions dehydrated and milled to a fine, free-flowing powder. Consistent pungency batch to batch.',
    featured: true,
    imageSrc: '/Images/Onion_Powder.png',
    rawImageSrc: '/Images/Onion_Powder.png',
    swatchImageSrc: '/Images/Onion_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Sauces'],
  },
  {
    id: '3',
    slug: 'garlic-powder',
    name: 'Garlic Powder',
    tagline: 'Pungent, warm, foundational',
    category: 'vegetable',
    swatchColor: 'pw-garlic',
    swatchHex: '#E8DCC8',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GAR-003',
    mesh: '100 mesh',
    description:
      'Whole garlic cloves, slow-dehydrated and hammer-milled for maximum allicin retention. A kitchen essential.',
    featured: false,
    imageSrc: '/Images/Garlic_Powder.png',
    rawImageSrc: '/Images/Garlic_Powder.png',
    swatchImageSrc: '/Images/Garlic_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Sauces'],
  },
  {
    id: '4',
    slug: 'beetroot-powder',
    name: 'Beetroot Powder',
    tagline: 'Vivid magenta, earthy sweet',
    category: 'vegetable',
    swatchColor: 'pw-beetroot',
    swatchHex: '#8B1A4A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-BET-004',
    mesh: '80 mesh',
    description:
      'Cold-processed beetroot preserving betalain pigments. Used as a natural food colorant and flavor base.',
    featured: true,
    imageSrc: '/Images/Beetroot_Powder.png',
    rawImageSrc: '/Images/Beetroot_Powder.png',
    swatchImageSrc: '/Images/Beetroot_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Cake Premixes', 'Confectionery', 'Pet Foods'],
  },
  {
    id: '5',
    slug: 'spinach-powder',
    name: 'Spinach Powder',
    tagline: 'Clean green, iron-rich',
    category: 'vegetable',
    swatchColor: 'pw-spinach',
    swatchHex: '#4A7C45',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-SPI-005',
    mesh: '100 mesh',
    description:
      'Baby spinach leaves spray-dried at low temperature. Neutral flavor profile — ideal for fortification.',
    featured: false,
    imageSrc: '/Images/Spinach_Powder.png',
    rawImageSrc: '/Images/Spinach_Powder.png',
    swatchImageSrc: '/Images/Spinach_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Extruder Foods', 'Instant Food Products'],
  },
  {
    id: '6',
    slug: 'ginger-powder',
    name: 'Ginger Powder',
    tagline: 'Fiery, warming, complex',
    category: 'spice',
    swatchColor: 'pw-ginger',
    swatchHex: '#C4892A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GIN-006',
    mesh: '80 mesh',
    description:
      'Rhizomes sourced from Rajasthan, dried and milled within 24 hours of processing. High gingerol content.',
    featured: false,
    imageSrc: '/Images/Ginger_Powder.png',
    rawImageSrc: '/Images/Ginger_Powder.png',
    swatchImageSrc: '/Images/Ginger_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Curries', 'Instant Food Products'],
  },
  {
    id: '7',
    slug: 'turmeric-powder',
    name: 'Turmeric Powder',
    tagline: 'Golden, earthy, 3% curcumin',
    category: 'spice',
    swatchColor: 'pw-turmeric',
    swatchHex: '#D4A017',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TUR-007',
    mesh: '100 mesh',
    description:
      'Lakadong variety turmeric with minimum 3% curcumin. Vivid golden color with minimal astringency. Excellent heat stability across a wide range of pH levels.',
    featured: true,
    imageSrc: '/Images/Turmeric_Powder.png',
    rawImageSrc: '/Images/Turmeric_Powder.png',
    swatchImageSrc: '/Images/Turmeric_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Dairy Products', 'Confectionery'],
  },
  {
    id: '8',
    slug: 'amla-powder',
    name: 'Amla Powder',
    tagline: 'Tart, astringent, vitamin C dense',
    category: 'fruit',
    swatchColor: 'pw-amla',
    swatchHex: '#6B8E3E',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-AML-008',
    mesh: '80 mesh',
    description:
      'Indian gooseberry dehydrated whole-fruit — retains tannins and ascorbic acid better than extract forms.',
    featured: false,
    imageSrc: '/Images/Amla_Powder.png',
    rawImageSrc: '/Images/Amla_Powder.png',
    swatchImageSrc: '/Images/Amla_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Spray Dried Fruit Powder Applications', 'Beverages', 'Confectionery'],
  },
  {
    id: '11',
    slug: 'green-mango-powder',
    name: 'Green Mango Powder',
    tagline: 'Sour, bright, amchur classic',
    category: 'fruit',
    swatchColor: 'pw-mango',
    swatchHex: '#8FA832',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-MAN-011',
    mesh: '80 mesh',
    description:
      'Raw alphonso mangoes sourced and sun-dried. Traditional amchur with consistent tartness and moisture below 8%.',
    featured: false,
    imageSrc: '/Images/GREEN_MANGO.png',
    rawImageSrc: '/Images/GREEN_MANGO.png',
    swatchImageSrc: '/Images/GREEN_MANGO.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Curries', 'Chutneys', 'Instant Food Mixes'],
  },
  {
    id: '12',
    slug: 'pomegranate-powder',
    name: 'Pomegranate Powder',
    tagline: 'Tart-sweet, ruby, antioxidant-high',
    category: 'fruit',
    swatchColor: 'pw-pomegranate',
    swatchHex: '#9B2335',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-POM-012',
    mesh: '100 mesh',
    description:
      'Whole pomegranate arils dehydrated and milled. Rich in punicalagins — used in nutraceutical formulations.',
    featured: false,
    imageSrc: '/Images/Pomegranate_Powder.png',
    rawImageSrc: '/Images/Pomegranate_Powder.png',
    swatchImageSrc: '/Images/Pomegranate_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Spray Dried Fruit Powder Applications', 'Nutraceutical Formulations', 'Beverages'],
  },
  {
    id: '13', slug: 'lemon-powder', name: 'Lemon Powder',
    tagline: 'Bright citrus, tangy zest', category: 'fruit',
    swatchColor: 'pw-lemon', swatchHex: '#F2C94C',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-LEM-013', mesh: '80 mesh',
    description: 'Spray-dried from fresh lemon concentrate. Vivid citrus aroma and tartness — no synthetic flavoring added.',
    featured: false,
    imageSrc: '/Images/Lemon_Powder.png', rawImageSrc: '/Images/Lemon_Powder.png', swatchImageSrc: '/Images/Lemon_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Beverages', 'Confectionery'],
  },
  {
    id: '14', slug: 'carrot-powder', name: 'Carrot Powder',
    tagline: 'Sweet, earthy, beta-carotene rich', category: 'vegetable',
    swatchColor: 'pw-carrot', swatchHex: '#E67E22',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CAR-014', mesh: '80 mesh',
    description: 'Fresh carrots washed, sorted, and spray-dried. Retains natural sweetness and vivid orange color.',
    featured: false,
    imageSrc: '/Images/Carrot_Powder.png', rawImageSrc: '/Images/Carrot_Powder.png', swatchImageSrc: '/Images/Carrot_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Baby Food', 'Instant Food Products'],
  },
  {
    id: '15', slug: 'annatto-colour', name: 'Annatto Colour',
    tagline: 'Natural orange-red food colorant', category: 'spice',
    swatchColor: 'pw-annatto', swatchHex: '#D9720B',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-ANN-015', mesh: '100 mesh',
    description: 'Derived from annatto seeds. Provides stable orange-red coloring across a wide pH range for food applications.',
    featured: false,
    imageSrc: '/Images/Annatto_Colour.png', rawImageSrc: '/Images/Annatto_Colour.png', swatchImageSrc: '/Images/Annatto_Colour.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Confectionery'],
  },
  {
    id: '16', slug: 'strawberry-powder', name: 'Strawberry Powder',
    tagline: 'Sweet, floral, ruby red', category: 'fruit',
    swatchColor: 'pw-strawberry', swatchHex: '#C8375A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-STR-016', mesh: '80 mesh',
    description: 'Spray-dried from ripe strawberries. Natural sweetness and aroma retained without added sugar.',
    featured: false,
    imageSrc: '/Images/Strawberry_Powder.png', rawImageSrc: '/Images/Strawberry_Powder.png', swatchImageSrc: '/Images/Strawberry_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '17', slug: 'orange-powder', name: 'Orange Powder',
    tagline: 'Zesty citrus, vitamin C rich', category: 'fruit',
    swatchColor: 'pw-orange', swatchHex: '#F39C12',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-ORA-017', mesh: '80 mesh',
    description: 'Freeze-dried from fresh oranges preserving natural citrus oils and vibrant color.',
    featured: false,
    imageSrc: '/Images/Orange_Powder.png', rawImageSrc: '/Images/Orange_Powder.png', swatchImageSrc: '/Images/Orange_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '18', slug: 'mango-powder', name: 'Mango Powder',
    tagline: 'Tropical, sweet, golden', category: 'fruit',
    swatchColor: 'pw-mangosweet', swatchHex: '#F5B041',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MNG-018', mesh: '80 mesh',
    description: 'Spray-dried from ripe Alphonso mangoes. Distinct from raw green mango (amchur) — this is sweet, ripe-fruit flavor.',
    featured: false,
    imageSrc: '/Images/Mango_Powder.png', rawImageSrc: '/Images/Mango_Powder.png', swatchImageSrc: '/Images/Mango_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '19', slug: 'banana-powder', name: 'Banana Powder',
    tagline: 'Naturally sweet, creamy aroma', category: 'fruit',
    swatchColor: 'pw-banana', swatchHex: '#F0E15A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-BAN-019', mesh: '80 mesh',
    description: 'Spray-dried from fresh banana pulp, preserving natural sweetness and characteristic aroma without any synthetic additives.',
    featured: false,
    imageSrc: '/Images/Banana_Powder.png', rawImageSrc: '/Images/Banana_Powder.png', swatchImageSrc: '/Images/Banana_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts', 'Nutraceuticals'],
  },
  {
    id: '20', slug: 'cheese-powder', name: 'Cheese Powder',
    tagline: 'Rich, savory, cheesy flavor', category: 'vegetable',
    swatchColor: 'pw-cheese', swatchHex: '#F5D580',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CHE-020', mesh: '80 mesh',
    description: 'Made from premium cheese sourced from reputed dairies. Versatile and convenient for numerous food manufacturing applications.',
    featured: false,
    imageSrc: '/Images/Cheese_Powder.png', rawImageSrc: '/Images/Cheese_Powder.png', swatchImageSrc: '/Images/Cheese_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Savoury', 'Snacks'],
  },
  {
    id: '21', slug: 'cream-powder', name: 'Cream Powder',
    tagline: 'Rich, smooth, dairy base', category: 'vegetable',
    swatchColor: 'pw-cream', swatchHex: '#FDF6E3',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CRM-021', mesh: '80 mesh',
    description: 'Sourced from premium dairy cream, spray-dried for extended shelf life. Used across bakery and dessert applications.',
    featured: false,
    imageSrc: '/Images/Cream_Powder.png', rawImageSrc: '/Images/Cream_Powder.png', swatchImageSrc: '/Images/Cream_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '22', slug: 'curd-powder', name: 'Curd Powder',
    tagline: 'Tangy, dairy, versatile', category: 'vegetable',
    swatchColor: 'pw-curd', swatchHex: '#FFFDF5',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CRD-022', mesh: '80 mesh',
    description: 'Sourced from fresh curd, spray-dried while retaining characteristic tang. Convenient for instant food formulations.',
    featured: false,
    imageSrc: '/Images/Curd_Powder.png', rawImageSrc: '/Images/Curd_Powder.png', swatchImageSrc: '/Images/Curd_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '23', slug: 'butter-powder', name: 'Butter Powder',
    tagline: 'Creamy, rich, buttery', category: 'vegetable',
    swatchColor: 'pw-butter', swatchHex: '#F7DC6F',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-BUT-023', mesh: '80 mesh',
    description: 'Sourced from premium dairy butter, dried to a stable powder form. Retains characteristic buttery aroma and mouthfeel.',
    featured: false,
    imageSrc: '/Images/Butter_Powder.png', rawImageSrc: '/Images/Butter_Powder.png', swatchImageSrc: '/Images/Butter_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '24', slug: 'caramel-colour', name: 'Caramel Colour',
    tagline: 'Deep brown, cola-standard', category: 'spice',
    swatchColor: 'pw-caramel', swatchHex: '#6B3E26',
    weights: ['1kg', '5kg', '25kg', '65kg', '200kg'], sku: 'NI-CML-024', mesh: 'Liquid / Powder',
    description: 'Class I through Class IV caramel colour available in jar or barrel packaging. Used across beverages, sauces, seasonings, and baked goods.',
    featured: false,
    imageSrc: '/Images/Caramel_Colour.png', rawImageSrc: '/Images/Caramel_Colour.png', swatchImageSrc: '/Images/Caramel_Colour.png',
    packagingSize: '1KG · 5KG · 25KG · 65KG · 200KG',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Cake Premixes', 'Confectionery', 'Pet Foods'],
  },
  {
    id: '25', slug: 'tamarind-powder', name: 'Tamarind Powder',
    tagline: 'Sour, tangy, traditional', category: 'fruit',
    swatchColor: 'pw-tamarind', swatchHex: '#7A5230',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-TAM-025', mesh: '80 mesh',
    description: 'Spray-dried from fresh tamarind pulp. A traditional souring agent for curries, chutneys, and instant food mixes.',
    featured: false,
    imageSrc: '/Images/Tamarind_Powder.png', rawImageSrc: '/Images/Tamarind_Powder.png', swatchImageSrc: '/Images/Tamarind_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Curries', 'Instant Food Products'],
  },
  {
    id: '26', slug: 'mint-powder', name: 'Mint Powder',
    tagline: 'Cool, fresh, aromatic', category: 'vegetable',
    swatchColor: 'pw-mint', swatchHex: '#7FB069',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MNT-026', mesh: '100 mesh',
    description: 'Fresh mint leaves dehydrated and milled. Adds cooling aroma to seasonings, beverages, and chutneys.',
    featured: false,
    imageSrc: '/Images/Mint_Powder.png', rawImageSrc: '/Images/Mint_Powder.png', swatchImageSrc: '/Images/Mint_Powder.png',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Seasonings', 'Beverages', 'Chutneys'],
  },
]

export const stats: Stat[] = [
  { value: '24+',       label: 'Powder Varieties' },
  { value: '500kg',     label: 'Min. Bulk Order'  },
  { value: '100%',      label: 'Additive-Free'    },
  { value: 'Est. 2011', label: 'Trusted Since'    },
]

export const processSteps: ProcessStep[] = [
  {
    tag: 'HARVEST',
    heading: 'Sourced at peak ripeness',
    body: 'We work directly with regional farms during harvest windows. Ingredients are selected when flavor compounds and pigments are at their highest concentration — not to a calendar schedule.',
  },
  {
    tag: 'DRY',
    heading: 'Low-temperature dehydration',
    body: 'All produce passes through drum, spray, or freeze-drying depending on the ingredient. We keep temperatures as low as the product allows — color, aroma, and nutrients stay intact.',
  },
  {
    tag: 'GRIND & PACK',
    heading: 'Milled to specification',
    body: 'Finished powders are hammer-milled to 80–100 mesh fineness, batch moisture-tested, and sealed in kraft paper or food-grade HDPE bags within the same shift.',
  },
]

export const extendedRange: ExtendedRangeItem[] = [
  { name: 'Green Chilly',       forms: 'Flakes · Powder' },
  { name: 'Mint Leaves',        forms: 'Leaves · Leaf Powder' },
  { name: 'Coriander',          forms: 'Leaves · Leaf Powder' },
  { name: 'Cabbage',            forms: 'Flakes · Powder' },
  { name: 'Kasuri Methi',       forms: 'Leaves · Leaf Powder' },
  { name: 'French Beans',       forms: 'Dehydrated' },
  { name: 'Sweet Potato',       forms: 'Powder' },
  { name: 'Potato',             forms: 'Flakes · Cubes · Powder' },
  { name: 'Bay Leaves',         forms: 'Leaves · Leaf Powder' },
  { name: 'Bitter Gourd',       forms: 'Flakes · Powder' },
  { name: 'Bottle Gourd',       forms: 'Powder' },
  { name: 'Okra',               forms: 'Powder' },
  { name: 'Parsley',            forms: 'Leaves' },
  { name: 'Isabgul (Psyllium)', forms: 'Husk' },
]
