import type { Product, Stat, ProcessStep } from '../types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'tomato-powder',
    name: 'Tomato Powder',
    tagline: 'Deep umami, rich lycopene',
    category: 'vegetable',
    swatchColor: 'pw-tomato',
    swatchHex: '#C23B22',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TOM-001',
    mesh: '80 mesh',
    description:
      'Made from ripe Roma tomatoes at peak harvest. Intense color, concentrated flavor — no added salt or sugar.',
    featured: true,
    imageSrc: '/Images/Tomato_Powder.jpg',
    rawImageSrc: '/Images/Tomato.jpg',
    swatchImageSrc: '/Images/Tomato.jpg',
  },
  {
    id: '2',
    slug: 'onion-powder',
    name: 'Onion Powder',
    tagline: 'Sharp, sulfurous, aromatic',
    category: 'vegetable',
    swatchColor: 'pw-onion',
    swatchHex: '#C9855A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-ONI-002',
    mesh: '80 mesh',
    description:
      'White onions dehydrated and milled to a fine, free-flowing powder. Consistent pungency batch to batch.',
    featured: true,
    imageSrc: '/Images/Onion_Powder.jpg',
    rawImageSrc: '/Images/Onion.jpg',
    swatchImageSrc: '/Images/Onion.jpg',
  },
  {
    id: '3',
    slug: 'garlic-powder',
    name: 'Garlic Powder',
    tagline: 'Pungent, warm, foundational',
    category: 'vegetable',
    swatchColor: 'pw-garlic',
    swatchHex: '#E8DCC8',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GAR-003',
    mesh: '100 mesh',
    description:
      'Whole garlic cloves, slow-dehydrated and hammer-milled for maximum allicin retention. A kitchen essential.',
    featured: false,
    imageSrc: '/Images/Garlic_Powder.jpg',
    rawImageSrc: '/Images/Garlic.jpg',
    swatchImageSrc: '/Images/Garlic.jpg',
  },
  {
    id: '4',
    slug: 'beetroot-powder',
    name: 'Beetroot Powder',
    tagline: 'Vivid magenta, earthy sweet',
    category: 'vegetable',
    swatchColor: 'pw-beetroot',
    swatchHex: '#8B1A4A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-BET-004',
    mesh: '80 mesh',
    description:
      'Cold-processed beetroot preserving betalain pigments. Used as a natural food colorant and flavor base.',
    featured: true,
    imageSrc: '/Images/Beetroot_Powder.jpg',
    rawImageSrc: '/Images/Beetroot.jpg',
    swatchImageSrc: '/Images/Beetroot.jpg',
  },
  {
    id: '5',
    slug: 'spinach-powder',
    name: 'Spinach Powder',
    tagline: 'Clean green, iron-rich',
    category: 'vegetable',
    swatchColor: 'pw-spinach',
    swatchHex: '#4A7C45',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-SPI-005',
    mesh: '100 mesh',
    description:
      'Baby spinach leaves spray-dried at low temperature. Neutral flavor profile — ideal for fortification.',
    featured: false,
    imageSrc: '/Images/Spinach_Powder.webp',
    rawImageSrc: '/Images/Spinach.jpg',
    swatchImageSrc: '/Images/Spinach.jpg',
  },
  {
    id: '6',
    slug: 'ginger-powder',
    name: 'Ginger Powder',
    tagline: 'Fiery, warming, complex',
    category: 'spice',
    swatchColor: 'pw-ginger',
    swatchHex: '#C4892A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GIN-006',
    mesh: '80 mesh',
    description:
      'Rhizomes sourced from Rajasthan, dried and milled within 24 hours of processing. High gingerol content.',
    featured: false,
    imageSrc: '/Images/Ginger_Powder.jpg',
    rawImageSrc: '/Images/Ginger.jpg',
    swatchImageSrc: '/Images/Ginger.jpg',
  },
  {
    id: '7',
    slug: 'turmeric-powder',
    name: 'Turmeric Powder',
    tagline: 'Golden, earthy, 3% curcumin',
    category: 'spice',
    swatchColor: 'pw-turmeric',
    swatchHex: '#D4A017',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TUR-007',
    mesh: '100 mesh',
    description:
      'Lakadong variety turmeric with minimum 3% curcumin. Vivid golden color with minimal astringency.',
    featured: true,
    imageSrc: '/Images/Turmeric_Powder.jpg',
    rawImageSrc: '/Images/Turmeric.jpg',
    swatchImageSrc: '/Images/Turmeric.jpg',
  },
  {
    id: '8',
    slug: 'amla-powder',
    name: 'Amla Powder',
    tagline: 'Tart, astringent, vitamin C dense',
    category: 'fruit',
    swatchColor: 'pw-amla',
    swatchHex: '#6B8E3E',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-AML-008',
    mesh: '80 mesh',
    description:
      'Indian gooseberry dehydrated whole-fruit — retains tannins and ascorbic acid better than extract forms.',
    featured: false,
    imageSrc: '/Images/Amla_Powder.png',
    rawImageSrc: '/Images/Amla.jpg',
    swatchImageSrc: '/Images/Amla.jpg',
  },
  {
    id: '9',
    slug: 'moringa-powder',
    name: 'Moringa Powder',
    tagline: 'Grassy, mild, nutrient-dense',
    category: 'vegetable',
    swatchColor: 'pw-moringa',
    swatchHex: '#3D6B35',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-MOR-009',
    mesh: '100 mesh',
    description:
      'Dried Moringa oleifera leaves, shade-dried to preserve chlorophyll and heat-sensitive amino acids.',
    featured: false,
    imageSrc: '/Images/Moringa_Powder.webp',
    rawImageSrc: '/Images/Moringa.jpg',
    swatchImageSrc: '/Images/Moringa.jpg',
  },
  {
    id: '10',
    slug: 'coconut-milk-powder',
    name: 'Coconut Milk Powder',
    tagline: 'Creamy, rich, 65% fat content',
    category: 'fruit',
    swatchColor: 'pw-coconut',
    swatchHex: '#F5EFE0',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-COC-010',
    mesh: '80 mesh',
    description:
      'Spray-dried from fresh coconut milk with a tapioca maltodextrin carrier. Reconstitutes cleanly in water.',
    featured: true,
    imageSrc: '/Images/Coconut_Powder.jpg',
    rawImageSrc: '/Images/Coconut.jpg',
    swatchImageSrc: '/Images/Coconut.jpg',
  },
  {
    id: '11',
    slug: 'green-mango-powder',
    name: 'Green Mango Powder',
    tagline: 'Sour, bright, amchur classic',
    category: 'fruit',
    swatchColor: 'pw-mango',
    swatchHex: '#8FA832',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-MAN-011',
    mesh: '80 mesh',
    description:
      'Raw alphonso mangoes sourced and sun-dried. Traditional amchur with consistent tartness and moisture below 8%.',
    featured: false,
    imageSrc: '/Images/Green-Mango_Powder1.jpg',
    rawImageSrc: '/Images/Green%20Mango.jpg',
    swatchImageSrc: '/Images/Green%20Mango.jpg',
  },
  {
    id: '12',
    slug: 'pomegranate-powder',
    name: 'Pomegranate Powder',
    tagline: 'Tart-sweet, ruby, antioxidant-high',
    category: 'fruit',
    swatchColor: 'pw-pomegranate',
    swatchHex: '#9B2335',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-POM-012',
    mesh: '100 mesh',
    description:
      'Whole pomegranate arils dehydrated and milled. Rich in punicalagins — used in nutraceutical formulations.',
    featured: false,
    imageSrc: '/Images/Pomegranate_Powder.jpg',
    rawImageSrc: '/Images/Pomegranate.jpg',
    swatchImageSrc: '/Images/Pomegranate.jpg',
  },
]

export const stats: Stat[] = [
  { value: '12+',       label: 'Powder Varieties' },
  { value: '500kg',     label: 'Min. Bulk Order'  },
  { value: '100%',      label: 'Additive-Free'    },
  { value: 'Est. 2011', label: 'Trusted Since'    },
]

export const processSteps: ProcessStep[] = [
  {
    tag: 'HARVEST',
    heading: 'Sourced at peak ripeness',
    body: 'We work directly with regional farms during harvest windows. Ingredients are selected when flavor compounds and pigments are at their highest concentration — not to a calendar schedule.',
  },
  {
    tag: 'DRY',
    heading: 'Low-temperature dehydration',
    body: 'All produce passes through drum, spray, or freeze-drying depending on the ingredient. We keep temperatures as low as the product allows — color, aroma, and nutrients stay intact.',
  },
  {
    tag: 'GRIND & PACK',
    heading: 'Milled to specification',
    body: 'Finished powders are hammer-milled to 80–100 mesh fineness, batch moisture-tested, and sealed in kraft paper or food-grade HDPE bags within the same shift.',
  },
]