import type { Product, Stat, ProcessStep, ExtendedRangeItem } from '../types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'tomato-powder',
    name: 'Tomato Powder',
    tagline: 'Deep umami, rich lycopene',
    category: 'vegetable',
    swatchColor: 'pw-tomato',
    swatchHex: '#C23B22',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TOM-001',
    mesh: '80 mesh',
    description:
      'Made from ripe Roma tomatoes at peak harvest. Intense color, concentrated flavor — no added salt or sugar.',
    featured: true,
    imageSrc: '/Images/Tomato_Powder.webp',
    rawImageSrc: '/Images/Tomato_Powder.webp',
    swatchImageSrc: '/Images/Tomato_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Extruder Foods', 'Curries', 'Instant Food Products'],
  },
  {
    id: '2',
    slug: 'onion-powder',
    name: 'Onion Powder',
    tagline: 'Sharp, sulfurous, aromatic',
    category: 'vegetable',
    swatchColor: 'pw-onion',
    swatchHex: '#C9855A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-ONI-002',
    mesh: '80 mesh',
    description:
      'White onions dehydrated and milled to a fine, free-flowing powder. Consistent pungency batch to batch.',
    featured: true,
    imageSrc: '/Images/Onion_Powder.webp',
    rawImageSrc: '/Images/Onion_Powder.webp',
    swatchImageSrc: '/Images/Onion_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Sauces'],
  },
  {
    id: '3',
    slug: 'garlic-powder',
    name: 'Garlic Powder',
    tagline: 'Pungent, warm, foundational',
    category: 'vegetable',
    swatchColor: 'pw-garlic',
    swatchHex: '#E8DCC8',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GAR-003',
    mesh: '100 mesh',
    description:
      'Whole garlic cloves, slow-dehydrated and hammer-milled for maximum allicin retention. A kitchen essential.',
    featured: false,
    imageSrc: '/Images/Garlic_Powder.webp',
    rawImageSrc: '/Images/Garlic_Powder.webp',
    swatchImageSrc: '/Images/Garlic_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Sauces'],
  },
  {
    id: '4',
    slug: 'beetroot-powder',
    name: 'Beetroot Powder',
    tagline: 'Vivid magenta, earthy sweet',
    category: 'vegetable',
    swatchColor: 'pw-beetroot',
    swatchHex: '#8B1A4A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-BET-004',
    mesh: '80 mesh',
    description:
      'Cold-processed beetroot preserving betalain pigments. Used as a natural food colorant and flavor base.',
    featured: true,
    imageSrc: '/Images/Beetroot_Powder.webp',
    rawImageSrc: '/Images/Beetroot_Powder.webp',
    swatchImageSrc: '/Images/Beetroot_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Cake Premixes', 'Confectionery', 'Pet Foods'],
  },
  {
    id: '5',
    slug: 'spinach-powder',
    name: 'Spinach Powder',
    tagline: 'Clean green, iron-rich',
    category: 'vegetable',
    swatchColor: 'pw-spinach',
    swatchHex: '#4A7C45',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-SPI-005',
    mesh: '100 mesh',
    description:
      'Baby spinach leaves spray-dried at low temperature. Neutral flavor profile — ideal for fortification.',
    featured: false,
    imageSrc: '/Images/Spinach_Powder.webp',
    rawImageSrc: '/Images/Spinach_Powder.webp',
    swatchImageSrc: '/Images/Spinach_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Extruder Foods', 'Instant Food Products'],
  },
  {
    id: '6',
    slug: 'ginger-powder',
    name: 'Ginger Powder',
    tagline: 'Fiery, warming, complex',
    category: 'spice',
    swatchColor: 'pw-ginger',
    swatchHex: '#C4892A',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-GIN-006',
    mesh: '80 mesh',
    description:
      'Rhizomes sourced from Rajasthan, dried and milled within 24 hours of processing. High gingerol content.',
    featured: false,
    imageSrc: '/Images/Ginger_Powder.webp',
    rawImageSrc: '/Images/Ginger_Powder.webp',
    swatchImageSrc: '/Images/Ginger_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Curries', 'Instant Food Products'],
  },
  {
    id: '7',
    slug: 'turmeric-powder',
    name: 'Turmeric Powder',
    tagline: 'Golden, earthy, 3% curcumin',
    category: 'spice',
    swatchColor: 'pw-turmeric',
    swatchHex: '#D4A017',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-TUR-007',
    mesh: '100 mesh',
    description:
      'Lakadong variety turmeric with minimum 3% curcumin. Vivid golden color with minimal astringency. Excellent heat stability across a wide range of pH levels.',
    featured: true,
    imageSrc: '/Images/Turmeric_Powder.webp',
    rawImageSrc: '/Images/Turmeric_Powder.webp',
    swatchImageSrc: '/Images/Turmeric_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Dairy Products', 'Confectionery'],
  },
  {
    id: '8',
    slug: 'amla-powder',
    name: 'Amla Powder',
    tagline: 'Tart, astringent, vitamin C dense',
    category: 'fruit',
    swatchColor: 'pw-amla',
    swatchHex: '#6B8E3E',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-AML-008',
    mesh: '80 mesh',
    description:
      'Indian gooseberry dehydrated whole-fruit — retains tannins and ascorbic acid better than extract forms.',
    featured: false,
    imageSrc: '/Images/Amla_Powder.webp',
    rawImageSrc: '/Images/Amla_Powder.webp',
    swatchImageSrc: '/Images/Amla_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Spray Dried Fruit Powder Applications', 'Beverages', 'Confectionery'],
  },
  {
    id: '11',
    slug: 'green-mango-powder',
    name: 'Green Mango Powder',
    tagline: 'Sour, bright, amchur classic',
    category: 'fruit',
    swatchColor: 'pw-mango',
    swatchHex: '#8FA832',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-MAN-011',
    mesh: '80 mesh',
    description:
      'Raw alphonso mangoes sourced and sun-dried. Traditional amchur with consistent tartness and moisture below 8%.',
    featured: false,
    imageSrc: '/Images/GREEN_MANGO.webp',
    rawImageSrc: '/Images/GREEN_MANGO.webp',
    swatchImageSrc: '/Images/GREEN_MANGO.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Curries', 'Chutneys', 'Instant Food Mixes'],
  },
  {
    id: '12',
    slug: 'pomegranate-powder',
    name: 'Pomegranate Powder',
    tagline: 'Tart-sweet, ruby, antioxidant-high',
    category: 'fruit',
    swatchColor: 'pw-pomegranate',
    swatchHex: '#9B2335',
    weights: ['1kg', '5kg', '25kg'],
    sku: 'NI-POM-012',
    mesh: '100 mesh',
    description:
      'Whole pomegranate arils dehydrated and milled. Rich in punicalagins — used in nutraceutical formulations.',
    featured: false,
    imageSrc: '/Images/Pomegranate_Powder.webp',
    rawImageSrc: '/Images/Pomegranate_Powder.webp',
    swatchImageSrc: '/Images/Pomegranate_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Spray Dried Fruit Powder Applications', 'Nutraceutical Formulations', 'Beverages'],
  },
  {
    id: '13', slug: 'lemon-powder', name: 'Lemon Powder',
    tagline: 'Bright citrus, tangy zest', category: 'fruit',
    swatchColor: 'pw-lemon', swatchHex: '#F2C94C',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-LEM-013', mesh: '80 mesh',
    description: 'Spray-dried from fresh lemon concentrate. Vivid citrus aroma and tartness — no synthetic flavoring added.',
    featured: false,
    imageSrc: '/Images/Lemon_Powder.webp', rawImageSrc: '/Images/Lemon_Powder.webp', swatchImageSrc: '/Images/Lemon_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Beverages', 'Confectionery'],
  },
  {
    id: '14', slug: 'carrot-powder', name: 'Carrot Powder',
    tagline: 'Sweet, earthy, beta-carotene rich', category: 'vegetable',
    swatchColor: 'pw-carrot', swatchHex: '#E67E22',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CAR-014', mesh: '80 mesh',
    description: 'Fresh carrots washed, sorted, and spray-dried. Retains natural sweetness and vivid orange color.',
    featured: false,
    imageSrc: '/Images/Carrot_Powder.webp', rawImageSrc: '/Images/Carrot_Powder.webp', swatchImageSrc: '/Images/Carrot_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Baby Food', 'Instant Food Products'],
  },
  {
    id: '15', slug: 'annatto-colour', name: 'Annatto Colour',
    tagline: 'Natural orange-red food colorant', category: 'spice',
    swatchColor: 'pw-annatto', swatchHex: '#D9720B',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-ANN-015', mesh: '100 mesh',
    description: 'Derived from annatto seeds. Provides stable orange-red coloring across a wide pH range for food applications.',
    featured: false,
    imageSrc: '/Images/Annatto_Colour.webp', rawImageSrc: '/Images/Annatto_Colour.webp', swatchImageSrc: '/Images/Annatto_Colour.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Confectionery'],
  },
  {
    id: '16', slug: 'strawberry-powder', name: 'Strawberry Powder',
    tagline: 'Sweet, floral, ruby red', category: 'fruit',
    swatchColor: 'pw-strawberry', swatchHex: '#C8375A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-STR-016', mesh: '80 mesh',
    description: 'Spray-dried from ripe strawberries. Natural sweetness and aroma retained without added sugar.',
    featured: false,
    imageSrc: '/Images/Strawberry_Powder.webp', rawImageSrc: '/Images/Strawberry_Powder.webp', swatchImageSrc: '/Images/Strawberry_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '17', slug: 'orange-powder', name: 'Orange Powder',
    tagline: 'Zesty citrus, vitamin C rich', category: 'fruit',
    swatchColor: 'pw-orange', swatchHex: '#F39C12',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-ORA-017', mesh: '80 mesh',
    description: 'Freeze-dried from fresh oranges preserving natural citrus oils and vibrant color.',
    featured: false,
    imageSrc: '/Images/Orange_Powder.webp', rawImageSrc: '/Images/Orange_Powder.webp', swatchImageSrc: '/Images/Orange_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '18', slug: 'mango-powder', name: 'Mango Powder',
    tagline: 'Tropical, sweet, golden', category: 'fruit',
    swatchColor: 'pw-mangosweet', swatchHex: '#F5B041',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MNG-018', mesh: '80 mesh',
    description: 'Spray-dried from ripe Alphonso mangoes. Distinct from raw green mango (amchur) — this is sweet, ripe-fruit flavor.',
    featured: false,
    imageSrc: '/Images/Mango_Powder.webp', rawImageSrc: '/Images/Mango_Powder.webp', swatchImageSrc: '/Images/Mango_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '19', slug: 'banana-powder', name: 'Banana Powder',
    tagline: 'Naturally sweet, creamy aroma', category: 'fruit',
    swatchColor: 'pw-banana', swatchHex: '#F0E15A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-BAN-019', mesh: '80 mesh',
    description: 'Spray-dried from fresh banana pulp, preserving natural sweetness and characteristic aroma without any synthetic additives.',
    featured: false,
    imageSrc: '/Images/Banana_Powder.webp', rawImageSrc: '/Images/Banana_Powder.webp', swatchImageSrc: '/Images/Banana_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts', 'Nutraceuticals'],
  },
  {
    id: '20', slug: 'cheese-powder', name: 'Cheese Powder',
    tagline: 'Rich, savory, cheesy flavor', category: 'vegetable',
    swatchColor: 'pw-cheese', swatchHex: '#F5D580',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CHE-020', mesh: '80 mesh',
    description: 'Made from premium cheese sourced from reputed dairies. Versatile and convenient for numerous food manufacturing applications.',
    featured: false,
    imageSrc: '/Images/Cheese_Powder.webp', rawImageSrc: '/Images/Cheese_Powder.webp', swatchImageSrc: '/Images/Cheese_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups & Savoury', 'Snacks'],
  },
  {
    id: '21', slug: 'cream-powder', name: 'Cream Powder',
    tagline: 'Rich, smooth, dairy base', category: 'vegetable',
    swatchColor: 'pw-cream', swatchHex: '#FDF6E3',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CRM-021', mesh: '80 mesh',
    description: 'Sourced from premium dairy cream, spray-dried for extended shelf life. Used across bakery and dessert applications.',
    featured: false,
    imageSrc: '/Images/Cream_Powder.webp', rawImageSrc: '/Images/Cream_Powder.webp', swatchImageSrc: '/Images/Cream_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '22', slug: 'curd-powder', name: 'Curd Powder',
    tagline: 'Tangy, dairy, versatile', category: 'vegetable',
    swatchColor: 'pw-curd', swatchHex: '#FFFDF5',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-CRD-022', mesh: '80 mesh',
    description: 'Sourced from fresh curd, spray-dried while retaining characteristic tang. Convenient for instant food formulations.',
    featured: false,
    imageSrc: '/Images/Curd_Powder.webp', rawImageSrc: '/Images/Curd_Powder.webp', swatchImageSrc: '/Images/Curd_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '23', slug: 'butter-powder', name: 'Butter Powder',
    tagline: 'Creamy, rich, buttery', category: 'vegetable',
    swatchColor: 'pw-butter', swatchHex: '#F7DC6F',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-BUT-023', mesh: '80 mesh',
    description: 'Sourced from premium dairy butter, dried to a stable powder form. Retains characteristic buttery aroma and mouthfeel.',
    featured: false,
    imageSrc: '/Images/Butter_Powder.webp', rawImageSrc: '/Images/Butter_Powder.webp', swatchImageSrc: '/Images/Butter_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Instant Food Products', 'Seasonings', 'Soups Savoury', 'Snacks'],
  },
  {
    id: '24', slug: 'caramel-colour', name: 'Caramel Colour',
    tagline: 'Deep brown, cola-standard', category: 'spice',
    swatchColor: 'pw-caramel', swatchHex: '#6B3E26',
    weights: ['1kg', '5kg', '25kg', '65kg', '200kg'], sku: 'NI-CML-024', mesh: 'Liquid / Powder',
    description: 'Class I through Class IV caramel colour available in jar or barrel packaging. Used across beverages, sauces, seasonings, and baked goods.',
    featured: false,
    imageSrc: '/Images/Caramel_Colour.webp', rawImageSrc: '/Images/Caramel_Colour.webp', swatchImageSrc: '/Images/Caramel_Colour.webp',
    packagingSize: '1KG · 5KG · 25KG · 65KG · 200KG',
    usageApplications: ['Beverages', 'Sauce & Seasoning', 'Baked Goods', 'Cake Premixes', 'Confectionery', 'Pet Foods'],
  },
  {
    id: '25', slug: 'tamarind-powder', name: 'Tamarind Powder',
    tagline: 'Sour, tangy, traditional', category: 'fruit',
    swatchColor: 'pw-tamarind', swatchHex: '#7A5230',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-TAM-025', mesh: '80 mesh',
    description: 'Spray-dried from fresh tamarind pulp. A traditional souring agent for curries, chutneys, and instant food mixes.',
    featured: false,
    imageSrc: '/Images/Tamarind_Powder.webp', rawImageSrc: '/Images/Tamarind_Powder.webp', swatchImageSrc: '/Images/Tamarind_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Curries', 'Instant Food Products'],
  },
  {
    id: '26', slug: 'mint-powder', name: 'Mint Powder',
    tagline: 'Cool, fresh, aromatic', category: 'vegetable',
    swatchColor: 'pw-mint', swatchHex: '#7FB069',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MNT-026', mesh: '100 mesh',
    description: 'Fresh mint leaves dehydrated and milled. Adds cooling aroma to seasonings, beverages, and chutneys.',
    featured: false,
    imageSrc: '/Images/Mint_Powder.webp', rawImageSrc: '/Images/Mint_Powder.webp', swatchImageSrc: '/Images/Mint_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Seasonings', 'Beverages', 'Chutneys'],
  },

  // ─── New Products (027–042) ───────────────────────────────────────────────
  {
    id: '27', slug: 'watermelon-powder', name: 'Watermelon Powder',
    tagline: 'Refreshing, light, summer sweet', category: 'fruit',
    swatchColor: 'pw-watermelon', swatchHex: '#FC5C7D',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-WML-027', mesh: '80 mesh',
    description: 'Spray-dried from fresh watermelon juice. Captures the refreshing sweetness and vivid colour of ripe watermelon without added sugars.',
    featured: false,
    imageSrc: '/Images/Watermelon_Powder.webp', rawImageSrc: '/Images/Watermelon_Powder.webp', swatchImageSrc: '/Images/Watermelon_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '28', slug: 'honey-powder', name: 'Honey Powder',
    tagline: 'Floral sweet, natural humectant', category: 'fruit',
    swatchColor: 'pw-honey', swatchHex: '#E8A020',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-HON-028', mesh: '80 mesh',
    description: 'Pure honey spray-dried onto a carrier. Retains floral aroma and natural sweetness — free-flowing, non-hygroscopic, shelf-stable.',
    featured: false,
    imageSrc: '/Images/Honey_Powder.webp', rawImageSrc: '/Images/Honey_Powder.webp', swatchImageSrc: '/Images/Honey_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Bakery', 'Beverage Premixes', 'Confectionery', 'Nutraceuticals', 'Seasonings'],
  },
  {
    id: '29', slug: 'jamun-powder', name: 'Jamun Powder',
    tagline: 'Deep purple, astringent, antioxidant-rich', category: 'fruit',
    swatchColor: 'pw-jamun', swatchHex: '#4B0082',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-JAM-029', mesh: '80 mesh',
    description: 'Java plum (Indian blackberry) dehydrated and milled. Rich in anthocyanins and traditionally valued for its low glycaemic properties.',
    featured: false,
    imageSrc: '/Images/Jamun_Powder.webp', rawImageSrc: '/Images/Jamun_Powder.webp', swatchImageSrc: '/Images/Jamun_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Nutraceuticals', 'Beverage Premixes', 'Confectionery', 'Instant Food Products'],
  },
  {
    id: '30', slug: 'kiwi-powder', name: 'Kiwi Powder',
    tagline: 'Tangy-sweet, bright green, vitamin C rich', category: 'fruit',
    swatchColor: 'pw-kiwi', swatchHex: '#5C8A00',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-KIW-030', mesh: '80 mesh',
    description: 'Spray-dried from ripe kiwifruit pulp. Distinctive tartness and high ascorbic acid content make it ideal for functional food applications.',
    featured: false,
    imageSrc: '/Images/Kiwi_Powder.webp', rawImageSrc: '/Images/Kiwi_Powder.webp', swatchImageSrc: '/Images/Kiwi_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Nutraceuticals'],
  },
  {
    id: '31', slug: 'lychee-powder', name: 'Lychee Powder',
    tagline: 'Delicate floral, tropical sweet', category: 'fruit',
    swatchColor: 'pw-lychee', swatchHex: '#F4A0A0',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-LYC-031', mesh: '80 mesh',
    description: 'Spray-dried from fresh lychee pulp. Preserves the delicate floral-sweet aroma and blush colour of the whole fruit.',
    featured: false,
    imageSrc: '/Images/Lychee_Powder.webp', rawImageSrc: '/Images/Lychee_Powder.webp', swatchImageSrc: '/Images/Lychee_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '32', slug: 'mulberry-powder', name: 'Mulberry Powder',
    tagline: 'Earthy berry, deep purple, antioxidant-dense', category: 'fruit',
    swatchColor: 'pw-mulberry', swatchHex: '#7B2D5E',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MUL-032', mesh: '80 mesh',
    description: 'Whole mulberries cold-processed and milled. High in resveratrol and anthocyanins — a premium superfruit ingredient.',
    featured: false,
    imageSrc: '/Images/Mulberry_Powder.webp', rawImageSrc: '/Images/Mulberry_Powder.webp', swatchImageSrc: '/Images/Mulberry_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Nutraceuticals', 'Beverage Premixes', 'Confectionery', 'Instant Food Products'],
  },
  {
    id: '33', slug: 'musk-melon-powder', name: 'Musk Melon Powder',
    tagline: 'Honeyed, mellow, summer fresh', category: 'fruit',
    swatchColor: 'pw-muskmelon', swatchHex: '#F7C873',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-MSK-033', mesh: '80 mesh',
    description: 'Spray-dried from ripe musk melon pulp. Mild honeyed sweetness makes it an excellent base for premium beverage and dessert premixes.',
    featured: false,
    imageSrc: '/Images/Musk_Melon_Powder.webp', rawImageSrc: '/Images/Musk_Melon_Powder.webp', swatchImageSrc: '/Images/Musk_Melon_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '34', slug: 'pineapple-powder', name: 'Pineapple Powder',
    tagline: 'Bright tropical, tart-sweet', category: 'fruit',
    swatchColor: 'pw-pineapple', swatchHex: '#FFD700',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-PIN-034', mesh: '80 mesh',
    description: 'Spray-dried from fresh pineapple juice. Intense tropical aroma and natural bromelain activity retained for functional food use.',
    featured: false,
    imageSrc: '/Images/Pineapple_Powder.webp', rawImageSrc: '/Images/Pineapple_Powder.webp', swatchImageSrc: '/Images/Pineapple_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Soups & Savoury'],
  },
  {
    id: '35', slug: 'pumpkin-powder', name: 'Pumpkin Powder',
    tagline: 'Earthy sweet, beta-carotene dense', category: 'vegetable',
    swatchColor: 'pw-pumpkin', swatchHex: '#E8722A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-PMP-035', mesh: '80 mesh',
    description: 'Ripe pumpkin flash-dried and milled. Naturally rich in beta-carotene and dietary fibre — excellent for baking, soups, and baby food formulations.',
    featured: false,
    imageSrc: '/Images/Pumpkin_Powder.webp', rawImageSrc: '/Images/Pumpkin_Powder.webp', swatchImageSrc: '/Images/Pumpkin_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Soup Premixes', 'Bakery', 'Instant Food Products', 'Nutraceuticals'],
  },
  {
    id: '36', slug: 'peach-powder', name: 'Peach Powder',
    tagline: 'Velvety, floral, stone-fruit sweet', category: 'fruit',
    swatchColor: 'pw-peach', swatchHex: '#FFAC7C',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-PCH-036', mesh: '80 mesh',
    description: 'Spray-dried from ripe peach pulp. Soft floral notes and natural sweetness — ideal for premium beverage and dessert formulations.',
    featured: false,
    imageSrc: '/Images/Peach_Powder.webp', rawImageSrc: '/Images/Peach_Powder.webp', swatchImageSrc: '/Images/Peach_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Baby Food', 'Beverage Premixes', 'Confectionery', 'Desserts'],
  },
  {
    id: '37', slug: 'raspberry-powder', name: 'Raspberry Powder',
    tagline: 'Tart, bright berry, deep ruby', category: 'fruit',
    swatchColor: 'pw-raspberry', swatchHex: '#C0006E',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-RAS-037', mesh: '80 mesh',
    description: 'Freeze-dried and milled from whole raspberries. Intense tartness and vivid colour — a premium flavour and natural colorant for confectionery and baked goods.',
    featured: false,
    imageSrc: '/Images/Raspberry_Powder.webp', rawImageSrc: '/Images/Raspberry_Powder.webp', swatchImageSrc: '/Images/Raspberry_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Bakery', 'Beverage Premixes', 'Confectionery', 'Nutraceuticals'],
  },
  {
    id: '38', slug: 'rose-petal-powder', name: 'Rose Petal Powder',
    tagline: 'Floral, delicate, aromatic', category: 'spice',
    swatchColor: 'pw-rosepetal', swatchHex: '#E8799A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-ROS-038', mesh: '80 mesh',
    description: 'Dried Damask rose petals cold-milled to a fine powder. Subtle floral fragrance and natural pink pigment for premium culinary and nutraceutical applications.',
    featured: false,
    imageSrc: '/Images/Rose_Petal_Powder.webp', rawImageSrc: '/Images/Rose_Petal_Powder.webp', swatchImageSrc: '/Images/Rose_Petal_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Bakery', 'Beverage Premixes', 'Confectionery', 'Nutraceuticals', 'Seasonings'],
  },
  {
    id: '39', slug: 'soya-hvp-powder', name: 'Soya HVP Powder',
    tagline: 'Deep umami, savory base, versatile', category: 'vegetable',
    swatchColor: 'pw-soyahvp', swatchHex: '#5C3D1E',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-SOY-039', mesh: '80 mesh',
    description: 'Hydrolysed Vegetable Protein derived from soya — spray-dried for easy incorporation. A powerful umami booster used widely in soups, seasonings, and instant food formulations.',
    featured: false,
    imageSrc: '/Images/Soya_HVP_Powder.webp', rawImageSrc: '/Images/Soya_HVP_Powder.webp', swatchImageSrc: '/Images/Soya_HVP_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Soup Premixes', 'Seasonings', 'Soups & Savoury', 'Instant Food Products', 'Snacks'],
  },
  {
    id: '40', slug: 'coconut-powder', name: 'Coconut Powder',
    tagline: 'Rich, tropical, creamy dairy-free base', category: 'fruit',
    swatchColor: 'pw-coconut', swatchHex: '#F5EDD8',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-COC-040', mesh: '80 mesh',
    description: 'Spray-dried from fresh coconut milk. Rich in medium-chain fatty acids with a clean creamy flavour — widely used as a dairy-free base in curries, beverages, and confectionery.',
    featured: false,
    imageSrc: '/Images/Coconut_Powder.webp', rawImageSrc: '/Images/Coconut_Powder.webp', swatchImageSrc: '/Images/Coconut_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Beverage Premixes', 'Confectionery', 'Soups & Savoury', 'Instant Food Products', 'Bakery'],
  },
  {
    id: '41', slug: 'green-chilly-powder', name: 'Green Chilly Powder',
    tagline: 'Sharp heat, grassy, fresh spice', category: 'vegetable',
    swatchColor: 'pw-greenchilly', swatchHex: '#3D7A2A',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-GCH-041', mesh: '80 mesh',
    description: 'Fresh green chillies dehydrated and milled. Delivers sharp pungency and grassy heat distinct from red chilli — ideal for authentic Indian spice blends and savoury premixes.',
    featured: false,
    imageSrc: '/Images/Green_Chilly_Powder.webp', rawImageSrc: '/Images/Green_Chilly_Powder.webp', swatchImageSrc: '/Images/Green_Chilly_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Seasonings', 'Soup Premixes', 'Soups & Savoury', 'Instant Food Products', 'Snacks'],
  },
  {
    id: '42', slug: 'coriander-powder', name: 'Coriander Powder',
    tagline: 'Citrusy, warm, classically herbal', category: 'vegetable',
    swatchColor: 'pw-coriander', swatchHex: '#7DB560',
    weights: ['1kg', '5kg', '25kg'], sku: 'NI-COR-042', mesh: '80 mesh',
    description: 'Coriander leaves dehydrated and milled to a fine herb powder. Fragrant citrus-herb character used across seasonings, chutneys, and savoury premixes.',
    featured: false,
    imageSrc: '/Images/Coriander_Powder.webp', rawImageSrc: '/Images/Coriander_Powder.webp', swatchImageSrc: '/Images/Coriander_Powder.webp',
    packagingSize: '25 KG Corrugated Box',
    usageApplications: ['Seasonings', 'Soup Premixes', 'Soups & Savoury', 'Instant Food Products', 'Chutneys'],
  },
]

export const stats: Stat[] = [
  { value: '40+',       label: 'Powder Varieties' },
  { value: '500kg',     label: 'Min. Bulk Order'  },
  { value: '100%',      label: 'Additive-Free'    },
  { value: 'Est. 2011', label: 'Trusted Since'    },
]

export const processSteps: ProcessStep[] = [
  {
    tag: 'HARVEST',
    heading: 'Sourced at peak ripeness',
    body: 'We work directly with regional farms during harvest windows. Ingredients are selected when flavor compounds and pigments are at their highest concentration — not to a calendar schedule.',
  },
  {
    tag: 'DRY',
    heading: 'Low-temperature dehydration',
    body: 'All produce passes through drum, spray, or freeze-drying depending on the ingredient. We keep temperatures as low as the product allows — color, aroma, and nutrients stay intact.',
  },
  {
    tag: 'GRIND & PACK',
    heading: 'Milled to specification',
    body: 'Finished powders are hammer-milled to 80-100 mesh fineness, batch moisture-tested, and sealed in kraft paper or food-grade HDPE bags within the same shift.',
  },
]

export const extendedRange: ExtendedRangeItem[] = [
  { name: 'Mint Leaves',        forms: 'Leaves · Leaf Powder' },
  { name: 'Cabbage',            forms: 'Flakes · Powder' },
  { name: 'Kasuri Methi',       forms: 'Leaves · Leaf Powder' },
  { name: 'French Beans',       forms: 'Dehydrated' },
  { name: 'Sweet Potato',       forms: 'Powder' },
  { name: 'Potato',             forms: 'Flakes · Cubes · Powder' },
  { name: 'Bay Leaves',         forms: 'Leaves · Leaf Powder' },
  { name: 'Bitter Gourd',       forms: 'Flakes · Powder' },
  { name: 'Bottle Gourd',       forms: 'Powder' },
  { name: 'Okra',               forms: 'Powder' },
  { name: 'Parsley',            forms: 'Leaves' },
  { name: 'Isabgul (Psyllium)', forms: 'Husk' },
]
